version: 2.1

jobs:
  build:
    docker:
      - image: circleci/ruby:3.0.0
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: portico_admin_api_test

    working_directory: ~/project

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            gem install bundler
            bundle install

      - run:
          name: Setup test database
          command: |
            bundle exec rake db:create
            bundle exec rake db:schema:load

      - run:
          name: Run tests
          command: |
            bundle exec rspec

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
