version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:3.0.0
      - image: circleci/postgres:14

    working_directory: ~/app

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            gem install bundler
            bundle install --jobs=4 --retry=3

      - run:
          name: Database setup
          command: |
            bundle exec rails db:create
            bundle exec rails db:schema:load
            bundle exec rails db:test:prepare

      - run:
          name: Run tests
          command: |
            bundle exec rspec # or your test suite command

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
