default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%=  ENV['POSTGRES_PASSWORD'] %>
  host: <%=  ENV['POSTGRES_HOST'] || 'localhost' %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: portico_admin_api_development

test:
  <<: *default
  database: portico_admin_api_test

production:
  <<: *default
  database: portico_admin_api_production
  username: portico_admin_api
  password: <%= ENV["PORTICO_ADMIN_API_DATABASE_PASSWORD"] %>
